version: '3.7'

services:
  api:
    build:
      context: api
      target: development
    hostname: api
    networks:
      - backend
    command:
      - /bin/sh
      - -c
      - |
        npm run start:dev
        npm run prisma:generate:watch
    restart: always
    ports:
      - "3100:80"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./api/:/api
      - /api/node_modules
      - /api/dist
    depends_on:
      - redis
      - crdb

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - backend
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

  crdb:
    image: cockroachdb/cockroach:v23.1.10
    ports:
      - "8080:8080"
    hostname: crdb
    networks:
      - backend
    command: start-single-node --insecure
    volumes:
      - crdb_data:/cockroach/cockroach-data

networks:
  backend:

volumes:
  postgres_data:
  crdb_data:
  redis_data:
